Alert
Arpit-dotcom/Component-Library pull request #3
Opened 2022-02-02 17:25 UTC by Arpit-dotcom

Alert component created

2022-02-02 19:42 UTC, rohanmathur91 commented on a
> +  main[m
what are this ?

2022-02-02 19:43 UTC, rohanmathur91 approved these changes
LGTM.

2022-02-02 19:58 UTC, surbhi84 requested changes
Add your html files as well, that'll help your peers to review your code better.
It is for future reference as well.

2022-02-03 04:55 UTC, shmbajaj requested changes
Hey add video or image, to visualize what your are trying to communicate.

2022-02-03 04:55 UTC, shmbajaj commented on css/style.css
> +}
Add new line here.

2022-02-03 04:55 UTC, shmbajaj commented on css/components/Alert.css
> +}
Add new line here.

2022-02-03 04:55 UTC, shmbajaj commented on a
> +  main[m
What these lines of code mean?

2022-02-03 05:32 UTC, Arpit-dotcom commented on a
> +  main[m
just unnecessary file

2022-02-03 05:35 UTC, Arpit-dotcom commented on a
> +  main[m
just unnecessary link

2022-02-03 05:36 UTC, Arpit-dotcom commented
![image](https://user-images.githubusercontent.com/86866251/152287241-4b24130e-b53b-44dc-a7d4-755f2c81013f.png)

2022-02-03 07:57 UTC, merged